### ISSUE TITLE
Incompatibility with Lithium

### ISSUE THREAD

**Issue by akiyuee** [PurpurMC/PurpurClient#16]
[Crash log 1](https://crashy.net/VbgoFs1cFJ0Cc37SMvQq) 
[Crash log 2 from my friend](https://crashy.net/6lUm2AsmLKqVfCYvauj1)
[Video from my friend](https://cdn.discordapp.com/attachments/685683819608670209/957884744207581194/Minecraft_2022.03.28_-_13.10.12.02.mp4)

Without Lithium installed:
![image](https://user-images.githubusercontent.com/67498765/161415543-3f980a41-2c06-4b70-a7bd-e931ee3dfce2.png)

**Comment by Scarlaid** [comment]
never thought I would see Rem riding a squid 👀
though I don't know what these offset settings for...

**Comment by EndermanHackerVN** [comment]
> never thought I would see Rem riding a squid 👀
> though I don't know what these offset settings for...

My best bet is it is a Purpur server exclusive feature of riding mobs
