### ISSUE TITLE
Incompatible with Pehkui

### ISSUE THREAD

**Issue by SplendidAlakey** [PurpurMC/PurpurClient#17]
**MC** 1.18.2
**Fabric API** 0.48.0
**[Pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui)** 3.2.1+1.14.4-1.19
**PurpurClient** 1.18.2-2

When both mods are present, the game will crash on init.

To reproduce simply install both mods + FAPI and try to launch the game.

Logs: https://gist.github.com/SplendidAlakey/e2e88fcf8c2e6b639a5066aaad6e3305

**Comment by dpe0** [comment]
same issue
