### ISSUE TITLE
Reason it did not compile

### ISSUE THREAD

**Issue by fxmorin** [PurpurMC/PurpurClient#2]
To use the chatLagFix from carpet-fixes you need to use:
`@Mixin(value = YggdrasilUserApiService.class, remap = false)`
For the Mixin, since it should not be remapped. That should fix your issue

**Comment by BillyGalbreath** [comment]
Makes sense ^_^ So far the hail mary seems to be ok, so we're gonna run with that (until it blows up, if it does). Will definitely keep this in mind if we have to revert.
