### ISSUE TITLE
Bundled Guava causes crash with FerriteCore

### ISSUE THREAD

**Issue by malte0811** [PurpurMC/PurpurClient#29]
You are currently bundling [Guava](https://github.com/PurpurMC/PurpurClient/blob/c3a79ff966a14256b38585c82f9d1cf3e9f17aac/build.gradle#L32) in your mod jar, the exact same version already supplied by MC. In FerriteCore I [define new classes](https://github.com/malte0811/FerriteCore/blob/7baeea0bd337188114f889c581a28f02b74f3364/Common/src/main/java/malte0811/ferritecore/classloading/FastImmutableMapDefiner.java) in a Guava package using `MethodHandles.Lookup#defineClass`. For some reason this silently fails when Guava is loaded from a jar-in-jar source on Quilt, see malte0811/FerriteCore#115 (this might be a bug in Quilt). It should be safe for you to stop bundling Guava since MC already supplies it, in my testing that worked and fixed the crash.

**Comment by Encode42** [comment]
Unfortunately, it is not safe for Guava to not be shaded. Configurate's HOCON library, for some reason, is having dependency issues without it. I'm personally not a client modder, nor do I have experience with Configurate, so I'm not sure how to debug the issue further. However, it was planned to drop Configurate entirely anyways.

**Comment by malte0811** [comment]
It looks like it's fixed in newer Quilt builds (apparently there were other issues in weird classloading situations), so disregard this.
