### ISSUE TITLE
MobsScreen is darker than it should be

### ISSUE THREAD

**Issue by Onako2** [PurpurMC/PurpurClient#38]
Minecraft 1.20.5 changed how backgrounds are handled. MobsScreen expects that there is a dirt background? When using contrast mode then it is completly black. OptionsSubScreens by default have the black background

![grafik](https://github.com/PurpurMC/PurpurClient/assets/79749977/936f3604-e6dc-4d4d-b6d9-4a7a49bf84e1)

**Comment by granny** [comment]
![image](https://github.com/PurpurMC/PurpurClient/assets/43185817/4d7cbcd1-e95b-4401-82a4-b8794102009f)
